secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
services:
  nginx:
    build: ./requirements/nginx
    container_name: inception_nginx
    restart: always
    ports:
      - "443:443"
    # volumes:
    #   - wordpress_data:/var/www/html:ro
    depends_on:
    #   - wordpress
      - mariadb
  mariadb:
    build: ./requirements/mariadb
    container_name: inceprion_mariadb
    restart: always
    ports:
      - "3306:3306"
    # volumes:
    #   - mariadb_data:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password
