services:
  nginx:
    build: ./requirements/nginx
    container_name: inception_nginx
    restart: always
    ports:
      - "443:443"
    # volumes:
    #   - wordpress_data:/var/www/html:ro
    # depends_on:
    #   - wordpress
    #   - mariadb
